// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr2E00GWdsLUmixVLpAkxsp9a2H3Yxm9s',
    appId: '1:475466786775:web:ae3b233212e04d556c8d92',
    messagingSenderId: '475466786775',
    projectId: 'cjp75yo-fb-auth-bloc',
    authDomain: 'cjp75yo-fb-auth-bloc.firebaseapp.com',
    storageBucket: 'cjp75yo-fb-auth-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtxyvt6sk6icgEf79rWABM6zwMTmvJ1fQ',
    appId: '1:475466786775:android:79dbe947ab58155e6c8d92',
    messagingSenderId: '475466786775',
    projectId: 'cjp75yo-fb-auth-bloc',
    storageBucket: 'cjp75yo-fb-auth-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPdvISHuR66kYK-3ddK84zLxh_hJmnhWs',
    appId: '1:475466786775:ios:a3e25704f83de6896c8d92',
    messagingSenderId: '475466786775',
    projectId: 'cjp75yo-fb-auth-bloc',
    storageBucket: 'cjp75yo-fb-auth-bloc.appspot.com',
    iosClientId: '475466786775-0ictd7q96n6oj4p3mcn6c0iqmg0g8g94.apps.googleusercontent.com',
    iosBundleId: 'com.example.cjpapp',
  );
}
